apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc1
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
