apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-busybox
  name: multi-busybox
spec:
  containers:
  - command: ["sh", "-c", "echo hello; sleep 3600"]
    image: busybox
    name: multi-busybox-1
    resources: {}
  - command: ["sh", "-c", "echo hello; sleep 3600"]
    image: busybox
    name: multi-busybox-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
