apiVersion: batch/v1
kind: Job
metadata:
  name: parallel
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: ctr
        image: alpine:latest
        command: ['sh', '-c', 'exit 1']
