apiVersion: batch/v1
kind: Job
metadata:
  name: parallel
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: ctr
        image: alpine:latest
        command: ['sh', '-c', 'echo "Lets smash the CKAD" && sleep 25']
